// <auto-generated />
using System;
using E_Commerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Commerce.Migrations
{
    [DbContext(typeof(E_CommerceDbContext))]
    [Migration("20220628141739_PcSeed")]
    partial class PcSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Commerce.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CartID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CartID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("E_Commerce.Models.Cart", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("E_Commerce.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Find all PCs and Laptops in our store here!",
                            Name = "PC && Laptops",
                            URL = "https://st2.depositphotos.com/1006689/10117/v/450/depositphotos_101178346-stock-illustration-laptop-computer-vector-icon.jpg"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Find Speakers and headsets in our store here!",
                            Name = "Audio Devices",
                            URL = "https://i.pinimg.com/736x/48/0c/da/480cda32088d4e5a1c0e4f53a2bb0fbc.jpg"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Find all Televitions in our store here!",
                            Name = "Televitions and Monitors",
                            URL = "https://i.pinimg.com/736x/5b/6c/d7/5b6cd7388dc2e7825191cfbd31e25c1d.jpg"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Find all moblie devices in our store here!",
                            Name = "Mobile Phones",
                            URL = "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/cell-phone-design-template-608242c6014c909324ec156c32889970_screen.jpg?ts=1581061060"
                        });
                });

            modelBuilder.Entity("E_Commerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3” 144Hz Full HD IPS-Type, Intel Core i7-11800H Processor, GeForce RTX 3050 Ti, 16GB DDR4, 512GB PCIe SSD, Gigabit Wi-Fi 6, Windows 10 Home, TUF706HEB-DB74",
                            InStock = true,
                            Name = "ASUS TUF Gaming F17 Gaming Laptop",
                            Price = 1149.99,
                            URL = ""
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 15.6 inch QHD Display, 240Hz Refresh Rate, Intel Core i7-11800H, 16GB DDR4 RAM, 512GB SSD, NVIDIA GeForce RTX 3070 8GB GDDR6, Windows 11- Black",
                            InStock = true,
                            Name = "Alienware M15 R6 VR Ready Gaming Laptop",
                            Price = 2173.98,
                            URL = ""
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Gaming/Creator Laptop | 12th Gen Intel i9-12900H | GeForce RTX 3080 Ti | 16inch WQXGA 240Hz G - SYNC Display | 32GB LPDDR5 | 1TB Gen 4x4 SSD | Killer Wi - Fi 6E | PT516 - 52s - 99EL",
                            InStock = true,
                            Name = "Acer Predator Triton 500 SE Gaming/Creator Laptop",
                            Price = 2989.9899999999998,
                            URL = ""
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "Gaming Laptop 15.6inch FHD IPS 144Hz 10th Gen Intel 6 - Core i7 - 10750H 16GB RAM 1TB PCIe SSD 6GB RTX 2060 RGB Backlit Win 10 + HDMI Cable",
                            InStock = true,
                            Name = "Acer Predator Helios 300 Gaming Laptop",
                            Price = 1699.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 1,
                            Description = "Gaming Laptop, Intel Core i5-10300H, NVIDIA GeForce RTX 3050, 16GB RAM, 512GB NVMe PCIe SSD, 15.6inch FHD 144Hz IPS Display, Wi-Fi 6, Backlit Keyboard, Windows 11 Home, JAWFOAL",
                            InStock = true,
                            Name = "Acer Nitro 5 Gaming Laptop",
                            Price = 899.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 1,
                            Description = "15.6inch Full HD IPS Display | 11th Gen Intel Core i3 - 1115G4 Processor | 4GB DDR4 | 128GB NVMe SSD | WiFi 6 | Windows 11 Home in S mode",
                            InStock = true,
                            Name = "Acer Aspire 5 A515 - 56 - 32DK Slim Laptop",
                            Price = 339.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3inch FHD 144Hz IPS Display, Intel Core i7-11800H, GeForce RTX 3060, 32GB RAM, 512GB SSD + 1TB SSD, Backlit KB, Wi-Fi 6, HDMI, Webcam, Windows 11 Home",
                            InStock = true,
                            Name = "Lenovo Legion 5i Gaming Laptop",
                            Price = 1799.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3inch Full HD Display, AMD Ryzen 5 5600H Processor, NVIDIA GeForce GTX 1650, 32GB RAM, 1TB SSD, Backlit Keyboard, Webcam, Wi-Fi 6, Windows 11 Home, Black",
                            InStock = true,
                            Name = "Lenovo Legion 5 Gaming Laptop",
                            Price = 999.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3inch Full HD Display, AMD Ryzen 5 5600H Processor, NVIDIA GeForce GTX 1650, 32GB RAM, 2TB SSD, Backlit Keyboard, Webcam, Wi-Fi 6, Windows 11 Home, Black",
                            InStock = true,
                            Name = "Lenovo Legion 5 Gaming Laptop",
                            Price = 1199.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 1,
                            Description = "16inch 165Hz QHD IPS Gaming Laptop, AMD Ryzen 7 5800H, NVIDIA GeForce RTX 3070,RGB Backlight, TGP 130W, 32GB RAM, 2TB PCIe SSD, Windows 10H, ES 32GB USB",
                            InStock = true,
                            Name = "Lenovo Legion 5 Pro",
                            Price = 1999.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 15.6inch Full HD IPS, Intel i7 CPU, 16GB DDR4 RAM, 256GB SSD, GeForce GTX 1060-6GB, VR Ready, Red Backlit KB, Metal Chassis, Windows 10 64-bit, G3-571-77QK",
                            InStock = true,
                            Name = "Acer Predator Helios 300 Gaming Laptop",
                            Price = 1278.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 1,
                            Description = "Geforce RTX 3060 2022 HP Pavilion Gaming Desktop PC, 32GB RAM, 1TB SSD+2TB HDD, Intel i5-10400F, Wired Mouse & Keyboard, Bluetooth, Wi-Fi, USB Type-C, Display Port, HDMI, Windows 11, Mouse Pad",
                            InStock = true,
                            Name = "2022 HP Pavilion Gaming Desktop PC",
                            Price = 1230.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 1,
                            Description = "ntel Core-i5 10400F 2.9GHz, RTX 3060 12GB GDDR6, 16GB DDR4 3000, 1TB SSD, 600W Gold PSU, AC WiFi, Windows 10",
                            InStock = true,
                            Name = "Skytech Shadow 3.0 Gaming PC Desktop",
                            Price = 1239.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 1,
                            Description = "Intel Core i5-11400F 2.6GHz, 8GB DDR4, GeForce RTX 2060 6GB, 500GB NVMe SSD, WiFi Ready & Win 11 Home (GXiVR8060A11)",
                            InStock = true,
                            Name = "CYBERPOWERPC Gamer Xtreme VR Gaming PC",
                            Price = 979.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 1,
                            Description = "NVIDIA GeForce GTX 1650 SUPER, Intel Core i3-10100, 8 GB DDR4 RAM, 256 GB PCIe NVMe SSD, Windows 11, USB Mouse and Keyboard, Compact Tower Design (TG01-1022, 2020)",
                            InStock = true,
                            Name = "HP Pavilion Gaming Desktop",
                            Price = 674.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 1,
                            Description = "Intel Core i7-12700F, 16GB DDR5 RAM, 512GB SSD + 1TB HDD, RTX 3060Ti LHR 8GB GDDR6, Air Cooled, USB-C, Killer WiFi 6, Bluetooth 5.2, Windows 11 Home - White",
                            InStock = true,
                            Name = "Alienware Aurora R13 Gaming Desktop",
                            Price = 1989.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 7-5800X 8-Core, GeForce RTX 3060 12GB, 32GB DDR4, 512GB PCIe SSD + 2TB HDD (3.5), WiFi-N, RGB Fans, 750W PSU, Win 10 Home)",
                            InStock = true,
                            Name = "Velztorm Galax CTO SFF Gaming Desktop PC",
                            Price = 1799.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 9 5900X 12-Core, 128GB DDR4, 8TB PCIe SSD + 6TB HDD (3.5), GeForce RTX 3090 24GB, WRGB Fans, AC WiFi, BT, Win 10 Home)",
                            InStock = true,
                            Name = "Velztorm Gladio CTO Powerful Gaming Desktop PC",
                            Price = 9478.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 1,
                            Description = "Intel Core i5 6500 3.2GHz, TechMagnet Siwa 6 with AMD RX-550 4GB DDR5, 16GB RAM, 256GB SSD, HDMI, DVI, VGA, RGB Keyboard, Mouse, Wi-Fi, Windows 10 Professional (Renewed)",
                            InStock = true,
                            Name = "Gaming PC Desktop, TechMagnet Siwa 6",
                            Price = 459.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 1,
                            Description = "AMD Ryzen 5 5600X 3.7GHz, GeForce RTX 3060 12GB, 16GB DDR4 RAM, 1TB NVMe SSD, WiFi Ready & Win 10 Home (GMA1410A3)",
                            InStock = true,
                            Name = "CYBERPOWERPC Gamer Master Gaming PC",
                            Price = 2021.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 1,
                            Description = "Intel i7 3.40GHz,16GB Ram,New 256GB SSD,Windows 10 Home,WiFi Ready,Video Card GT 1030 2GB, RGB Fans,80+ 500W Power Supply",
                            InStock = true,
                            Name = "TJJ Halo Gaming PC Desktop Computer",
                            Price = 599.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 1,
                            Description = "AMD Octa-Core Ryzen 7 5800X (Beats i9-10900X) 64GB RAM 1TB SSD + 1TB HDD GeForce RTX 3070 8GB Graphic DisplayPort DVI Win10 Black + HDMI Cable",
                            InStock = true,
                            Name = "ASUS ROG Strix GA15 Gaming Desktop Computer",
                            Price = 2499.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 1,
                            Description = "Intel Core i9 12900K 3.2 GHz, RTX 3090, 1TB NVME Gen4 SSD, 32G DDR5 RGB, 850W Gold PSU, 360mm AIO, AC Wi-Fi, Windows 10 Home 64-bit",
                            InStock = true,
                            Name = "Skytech Prism II Gaming PC Desktop",
                            Price = 4499.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 7-5800X 8-Core, Radeon RX 6900 XT 16GB, 128GB DDR4, 8TB PCIe SSD+6TB HDD (3.5), WiFi-N, RGB Fans, 750W PSU, Black, Win 10 Pro)",
                            InStock = true,
                            Name = "Velztorm Galax CTO SFF Gaming Desktop PC",
                            Price = 9548.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 1,
                            Description = "Intel i7-11700 - 32GB RAM, 512GB NVMe SSD + 1TB HDD - Nvidia Geforce RTX 3060 Ti 8GB 4K, DisplayPort, HDMI, DVD, AX Wi-Fi, Bluetooth, SD Card - Windows 10 Pro (Renewed)",
                            InStock = true,
                            Name = "Dell XPS 8940 Gaming Tower PC",
                            Price = 1463.4000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 1,
                            Description = "Ryzen 5 3600 6-Core 3.6GHz, RTX 3060 12GB, 1TB SSD, 16GB DDR4 3000, RGB Fans, AC WiFi, 600W Gold PSU, Windows 10 Home 64-bit, Black",
                            InStock = true,
                            Name = "SkyTech Shadow 3.0 Gaming Computer PC Desktop",
                            Price = 1199.99,
                            URL = ""
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 1,
                            Description = "AMD Ryzen 7 5800, NVIDIA GeForce RTX 3070 8GB GDDR6, 16GB 3466MHz RAM, 512GB SSD + 1TB HDD, Air Cooled, Wi-Fi 6, Bluetooth, USB-C, Windows 11 Home - Black",
                            InStock = true,
                            Name = "Alienware Aurora R14 VR Ready Gaming PC",
                            Price = 1800.96,
                            URL = ""
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 9 5900X 12-Core, 32GB DDR4, 1TB PCIe SSD + 1TB HDD (3.5), GeForce RTX 3070 8GB, WRGB Fans, AC WiFi, BT, Win 10 Pro)",
                            InStock = true,
                            Name = "Velztorm Gladio CTO Powerful Gaming Desktop PC",
                            Price = 2264.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 1,
                            Description = "AMD Ryzen 9 5950X 16-Core/32-Thread Processor, 32GB ARGB 3200MHz DDR4, NVIDIA GeForce RTX 3080 12GB, 2TB M.2 NVMe SSD, WiFi + Bluetooth, Windows 11",
                            InStock = true,
                            Name = "MEK Hero G1 A5938V2 Gaming Desktop Powered by ZOTAC",
                            Price = 3101.9899999999998,
                            URL = ""
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 1,
                            Description = "AMD Ryzen 7 5800X, GeForce RTX 3070, 16GB DDR4 RAM, 1TB SSD, Windows 10 Home, GA15DK-DS776",
                            InStock = true,
                            Name = "ROG Strix GA15 Gaming Desktop PC",
                            Price = 1864.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 31,
                            CategoryID = 1,
                            Description = "AMD Ryzen 7 5700G, 16 GB RAM, 512 GB SSD, Windows 11 Pro, Wi-Fi 5 & Bluetooth Connectivity, 9 USB Ports, Wired Mouse and Keyboard Combo, Pre-Built Tower (TP01-2022, 2021)",
                            InStock = true,
                            Name = "HP Pavilion Desktop PC",
                            Price = 809.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 32,
                            CategoryID = 1,
                            Description = "AMD Radeon RX 5500, AMD Ryzen 5 3500, HyperX 8GB DDR4 RAM, 512GB PCIe NVMe SSD, Windows 10 Home, VR Ready, RGB Lighting (GT12-0010, 2020 Model)",
                            InStock = true,
                            Name = "OMEN 25L Gaming Desktop PC",
                            Price = 999.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 33,
                            CategoryID = 1,
                            Description = "A descktop pc with great performance",
                            InStock = true,
                            Name = "iMac Retina",
                            Price = 1500.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 34,
                            CategoryID = 1,
                            Description = "Dell OptiPlex 7780 All-in-One 10Gen Intel Core i7 up to 4.8GHz 16M 6-Cores , 8GB RAM DDR4 (upgradable) , 256 GB Gen 3 PCIe x4 NVMe SSD + 1TB HDD , 27inch WVA Full HD 250nits Screen, NO Optical Drive,Intel UHD 630 Graphic Card,",
                            InStock = true,
                            Name = "Dell OptiPlex 7780 All-in-One All-in-One 10Gen Intel Core i7 w/ Adjustable 27inch Touch",
                            Price = 1000.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 35,
                            CategoryID = 2,
                            Description = "5.1 digital surround sound: Hear every detail in your Dolby Digital and DTS soundtracks the way the studio intended. Sub woofer: 165 Watts",
                            InStock = true,
                            Name = "Logitech Z906 5.1 Surround Sound Speaker System THX, Dolby Digital & DTS Digital Certified",
                            Price = 100.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 36,
                            CategoryID = 2,
                            Description = "High performance speaker system that produces 50 Watts of raw, rock solid audio power",
                            InStock = true,
                            Name = "Creative SBS E2800 2.1 High Performance Speakers System - Black",
                            Price = 55.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 37,
                            CategoryID = 3,
                            Description = "4-Series 4K UHD smart TV",
                            InStock = true,
                            Name = "Amazon Fire TV 43",
                            Price = 250.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 38,
                            CategoryID = 3,
                            Description = "Class LED 4K UHD Smart Fire TV (PN43951-22U, 2021 Model)",
                            InStock = true,
                            Name = "Pioneer 43-inch",
                            Price = 210.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 39,
                            CategoryID = 4,
                            Description = "Apple Flagship mobile phone with 256GB",
                            InStock = false,
                            Name = "iPhone 13 Pro Max",
                            Price = 1200.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 40,
                            CategoryID = 4,
                            Description = "Samsung Flagship mobile phone with 256GB",
                            InStock = true,
                            Name = "Samsung Galaxy S22 Ultra",
                            Price = 1000.0,
                            URL = "https://shop.samsung.com/ie/images/products/28636/21040/2000x2000/SM-S908BZKDEUB.webp"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "administrator",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "editor",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "user",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissions",
                            ClaimValue = "create",
                            RoleId = "administrator"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissions",
                            ClaimValue = "delete",
                            RoleId = "administrator"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissions",
                            ClaimValue = "create",
                            RoleId = "editor"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissions",
                            ClaimValue = "update",
                            RoleId = "editor"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissions",
                            ClaimValue = "create",
                            RoleId = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("E_Commerce.Models.ApplicationUser", b =>
                {
                    b.HasOne("E_Commerce.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartID");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("E_Commerce.Models.Product", b =>
                {
                    b.HasOne("E_Commerce.Models.Cart", null)
                        .WithMany("Products")
                        .HasForeignKey("CartID");

                    b.HasOne("E_Commerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce.Models.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
