// <auto-generated />
using System;
using E_Commerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Commerce.Migrations
{
    [DbContext(typeof(E_CommerceDbContext))]
    [Migration("20220628192321_RemoveURL")]
    partial class RemoveURL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Commerce.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CartID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CartID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("E_Commerce.Models.Cart", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("E_Commerce.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Find all PCs and Laptops in our store here!",
                            Name = "PCs And Laptops",
                            URL = "https://st2.depositphotos.com/1006689/10117/v/450/depositphotos_101178346-stock-illustration-laptop-computer-vector-icon.jpg"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Find Speakers and headsets in our store here!",
                            Name = "Audio Devices",
                            URL = "https://i.pinimg.com/736x/48/0c/da/480cda32088d4e5a1c0e4f53a2bb0fbc.jpg"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Find all Televitions in our store here!",
                            Name = "Televitions and Monitors",
                            URL = "https://i.pinimg.com/736x/5b/6c/d7/5b6cd7388dc2e7825191cfbd31e25c1d.jpg"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Find all moblie devices in our store here!",
                            Name = "Mobile Phones",
                            URL = "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/cell-phone-design-template-608242c6014c909324ec156c32889970_screen.jpg?ts=1581061060"
                        });
                });

            modelBuilder.Entity("E_Commerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3” 144Hz Full HD IPS-Type, Intel Core i7-11800H Processor, GeForce RTX 3050 Ti, 16GB DDR4, 512GB PCIe SSD, Gigabit Wi-Fi 6, Windows 10 Home, TUF706HEB-DB74",
                            InStock = true,
                            Name = "ASUS TUF Gaming F17 Gaming Laptop",
                            Price = 1149.99
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 15.6 inch QHD Display, 240Hz Refresh Rate, Intel Core i7-11800H, 16GB DDR4 RAM, 512GB SSD, NVIDIA GeForce RTX 3070 8GB GDDR6, Windows 11- Black",
                            InStock = true,
                            Name = "Alienware M15 R6 VR Ready Gaming Laptop",
                            Price = 2173.98,
                            URL = ""
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Gaming/Creator Laptop | 12th Gen Intel i9-12900H | GeForce RTX 3080 Ti | 16inch WQXGA 240Hz G - SYNC Display | 32GB LPDDR5 | 1TB Gen 4x4 SSD | Killer Wi - Fi 6E | PT516 - 52s - 99EL",
                            InStock = true,
                            Name = "Acer Predator Triton 500 SE Gaming/Creator Laptop",
                            Price = 2989.9899999999998,
                            URL = ""
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "Gaming Laptop 15.6inch FHD IPS 144Hz 10th Gen Intel 6 - Core i7 - 10750H 16GB RAM 1TB PCIe SSD 6GB RTX 2060 RGB Backlit Win 10 + HDMI Cable",
                            InStock = true,
                            Name = "Acer Predator Helios 300 Gaming Laptop",
                            Price = 1699.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 1,
                            Description = "Gaming Laptop, Intel Core i5-10300H, NVIDIA GeForce RTX 3050, 16GB RAM, 512GB NVMe PCIe SSD, 15.6inch FHD 144Hz IPS Display, Wi-Fi 6, Backlit Keyboard, Windows 11 Home, JAWFOAL",
                            InStock = true,
                            Name = "Acer Nitro 5 Gaming Laptop",
                            Price = 899.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 1,
                            Description = "15.6inch Full HD IPS Display | 11th Gen Intel Core i3 - 1115G4 Processor | 4GB DDR4 | 128GB NVMe SSD | WiFi 6 | Windows 11 Home in S mode",
                            InStock = true,
                            Name = "Acer Aspire 5 A515 - 56 - 32DK Slim Laptop",
                            Price = 339.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3inch FHD 144Hz IPS Display, Intel Core i7-11800H, GeForce RTX 3060, 32GB RAM, 512GB SSD + 1TB SSD, Backlit KB, Wi-Fi 6, HDMI, Webcam, Windows 11 Home",
                            InStock = true,
                            Name = "Lenovo Legion 5i Gaming Laptop",
                            Price = 1799.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3inch Full HD Display, AMD Ryzen 5 5600H Processor, NVIDIA GeForce GTX 1650, 32GB RAM, 1TB SSD, Backlit Keyboard, Webcam, Wi-Fi 6, Windows 11 Home, Black",
                            InStock = true,
                            Name = "Lenovo Legion 5 Gaming Laptop",
                            Price = 999.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 17.3inch Full HD Display, AMD Ryzen 5 5600H Processor, NVIDIA GeForce GTX 1650, 32GB RAM, 2TB SSD, Backlit Keyboard, Webcam, Wi-Fi 6, Windows 11 Home, Black",
                            InStock = true,
                            Name = "Lenovo Legion 5 Gaming Laptop",
                            Price = 1199.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 1,
                            Description = "16inch 165Hz QHD IPS Gaming Laptop, AMD Ryzen 7 5800H, NVIDIA GeForce RTX 3070,RGB Backlight, TGP 130W, 32GB RAM, 2TB PCIe SSD, Windows 10H, ES 32GB USB",
                            InStock = true,
                            Name = "Lenovo Legion 5 Pro",
                            Price = 1999.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 1,
                            Description = "Gaming Laptop, 15.6inch Full HD IPS, Intel i7 CPU, 16GB DDR4 RAM, 256GB SSD, GeForce GTX 1060-6GB, VR Ready, Red Backlit KB, Metal Chassis, Windows 10 64-bit, G3-571-77QK",
                            InStock = true,
                            Name = "Acer Predator Helios 300 Gaming Laptop",
                            Price = 1278.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 1,
                            Description = "Geforce RTX 3060 2022 HP Pavilion Gaming Desktop PC, 32GB RAM, 1TB SSD+2TB HDD, Intel i5-10400F, Wired Mouse & Keyboard, Bluetooth, Wi-Fi, USB Type-C, Display Port, HDMI, Windows 11, Mouse Pad",
                            InStock = true,
                            Name = "2022 HP Pavilion Gaming Desktop PC",
                            Price = 1230.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 1,
                            Description = "ntel Core-i5 10400F 2.9GHz, RTX 3060 12GB GDDR6, 16GB DDR4 3000, 1TB SSD, 600W Gold PSU, AC WiFi, Windows 10",
                            InStock = true,
                            Name = "Skytech Shadow 3.0 Gaming PC Desktop",
                            Price = 1239.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 1,
                            Description = "Intel Core i5-11400F 2.6GHz, 8GB DDR4, GeForce RTX 2060 6GB, 500GB NVMe SSD, WiFi Ready & Win 11 Home (GXiVR8060A11)",
                            InStock = true,
                            Name = "CYBERPOWERPC Gamer Xtreme VR Gaming PC",
                            Price = 979.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 1,
                            Description = "NVIDIA GeForce GTX 1650 SUPER, Intel Core i3-10100, 8 GB DDR4 RAM, 256 GB PCIe NVMe SSD, Windows 11, USB Mouse and Keyboard, Compact Tower Design (TG01-1022, 2020)",
                            InStock = true,
                            Name = "HP Pavilion Gaming Desktop",
                            Price = 674.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 1,
                            Description = "Intel Core i7-12700F, 16GB DDR5 RAM, 512GB SSD + 1TB HDD, RTX 3060Ti LHR 8GB GDDR6, Air Cooled, USB-C, Killer WiFi 6, Bluetooth 5.2, Windows 11 Home - White",
                            InStock = true,
                            Name = "Alienware Aurora R13 Gaming Desktop",
                            Price = 1989.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 7-5800X 8-Core, GeForce RTX 3060 12GB, 32GB DDR4, 512GB PCIe SSD + 2TB HDD (3.5), WiFi-N, RGB Fans, 750W PSU, Win 10 Home)",
                            InStock = true,
                            Name = "Velztorm Galax CTO SFF Gaming Desktop PC",
                            Price = 1799.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 9 5900X 12-Core, 128GB DDR4, 8TB PCIe SSD + 6TB HDD (3.5), GeForce RTX 3090 24GB, WRGB Fans, AC WiFi, BT, Win 10 Home)",
                            InStock = true,
                            Name = "Velztorm Gladio CTO Powerful Gaming Desktop PC",
                            Price = 9478.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 1,
                            Description = "Intel Core i5 6500 3.2GHz, TechMagnet Siwa 6 with AMD RX-550 4GB DDR5, 16GB RAM, 256GB SSD, HDMI, DVI, VGA, RGB Keyboard, Mouse, Wi-Fi, Windows 10 Professional (Renewed)",
                            InStock = true,
                            Name = "Gaming PC Desktop, TechMagnet Siwa 6",
                            Price = 459.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 1,
                            Description = "AMD Ryzen 5 5600X 3.7GHz, GeForce RTX 3060 12GB, 16GB DDR4 RAM, 1TB NVMe SSD, WiFi Ready & Win 10 Home (GMA1410A3)",
                            InStock = true,
                            Name = "CYBERPOWERPC Gamer Master Gaming PC",
                            Price = 2021.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 1,
                            Description = "Intel i7 3.40GHz,16GB Ram,New 256GB SSD,Windows 10 Home,WiFi Ready,Video Card GT 1030 2GB, RGB Fans,80+ 500W Power Supply",
                            InStock = true,
                            Name = "TJJ Halo Gaming PC Desktop Computer",
                            Price = 599.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 1,
                            Description = "AMD Octa-Core Ryzen 7 5800X (Beats i9-10900X) 64GB RAM 1TB SSD + 1TB HDD GeForce RTX 3070 8GB Graphic DisplayPort DVI Win10 Black + HDMI Cable",
                            InStock = true,
                            Name = "ASUS ROG Strix GA15 Gaming Desktop Computer",
                            Price = 2499.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 1,
                            Description = "Intel Core i9 12900K 3.2 GHz, RTX 3090, 1TB NVME Gen4 SSD, 32G DDR5 RGB, 850W Gold PSU, 360mm AIO, AC Wi-Fi, Windows 10 Home 64-bit",
                            InStock = true,
                            Name = "Skytech Prism II Gaming PC Desktop",
                            Price = 4499.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 7-5800X 8-Core, Radeon RX 6900 XT 16GB, 128GB DDR4, 8TB PCIe SSD+6TB HDD (3.5), WiFi-N, RGB Fans, 750W PSU, Black, Win 10 Pro)",
                            InStock = true,
                            Name = "Velztorm Galax CTO SFF Gaming Desktop PC",
                            Price = 9548.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 1,
                            Description = "Intel i7-11700 - 32GB RAM, 512GB NVMe SSD + 1TB HDD - Nvidia Geforce RTX 3060 Ti 8GB 4K, DisplayPort, HDMI, DVD, AX Wi-Fi, Bluetooth, SD Card - Windows 10 Pro (Renewed)",
                            InStock = true,
                            Name = "Dell XPS 8940 Gaming Tower PC",
                            Price = 1463.4000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 1,
                            Description = "Ryzen 5 3600 6-Core 3.6GHz, RTX 3060 12GB, 1TB SSD, 16GB DDR4 3000, RGB Fans, AC WiFi, 600W Gold PSU, Windows 10 Home 64-bit, Black",
                            InStock = true,
                            Name = "SkyTech Shadow 3.0 Gaming Computer PC Desktop",
                            Price = 1199.99,
                            URL = ""
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 1,
                            Description = "AMD Ryzen 7 5800, NVIDIA GeForce RTX 3070 8GB GDDR6, 16GB 3466MHz RAM, 512GB SSD + 1TB HDD, Air Cooled, Wi-Fi 6, Bluetooth, USB-C, Windows 11 Home - Black",
                            InStock = true,
                            Name = "Alienware Aurora R14 VR Ready Gaming PC",
                            Price = 1800.96,
                            URL = ""
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 1,
                            Description = "Liquid-Cooled (AMD Ryzen 9 5900X 12-Core, 32GB DDR4, 1TB PCIe SSD + 1TB HDD (3.5), GeForce RTX 3070 8GB, WRGB Fans, AC WiFi, BT, Win 10 Pro)",
                            InStock = true,
                            Name = "Velztorm Gladio CTO Powerful Gaming Desktop PC",
                            Price = 2264.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 1,
                            Description = "AMD Ryzen 9 5950X 16-Core/32-Thread Processor, 32GB ARGB 3200MHz DDR4, NVIDIA GeForce RTX 3080 12GB, 2TB M.2 NVMe SSD, WiFi + Bluetooth, Windows 11",
                            InStock = true,
                            Name = "MEK Hero G1 A5938V2 Gaming Desktop Powered by ZOTAC",
                            Price = 3101.9899999999998,
                            URL = ""
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 1,
                            Description = "AMD Ryzen 7 5800X, GeForce RTX 3070, 16GB DDR4 RAM, 1TB SSD, Windows 10 Home, GA15DK-DS776",
                            InStock = true,
                            Name = "ROG Strix GA15 Gaming Desktop PC",
                            Price = 1864.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 31,
                            CategoryID = 1,
                            Description = "AMD Ryzen 7 5700G, 16 GB RAM, 512 GB SSD, Windows 11 Pro, Wi-Fi 5 & Bluetooth Connectivity, 9 USB Ports, Wired Mouse and Keyboard Combo, Pre-Built Tower (TP01-2022, 2021)",
                            InStock = true,
                            Name = "HP Pavilion Desktop PC",
                            Price = 809.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 32,
                            CategoryID = 1,
                            Description = "AMD Radeon RX 5500, AMD Ryzen 5 3500, HyperX 8GB DDR4 RAM, 512GB PCIe NVMe SSD, Windows 10 Home, VR Ready, RGB Lighting (GT12-0010, 2020 Model)",
                            InStock = true,
                            Name = "OMEN 25L Gaming Desktop PC",
                            Price = 999.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 33,
                            CategoryID = 2,
                            Description = "SUPERIOR DYNAMIC QUALITY | Milan delivers 5.1 surround sound using uncompressed 24-bit 48 kHz audio signal (Milan delivers 3.1 sound using uncompressed 24-bit 48 kHz audio signal), far beyond Bluetooth capabilities. The SoundSend transmitter decodes theatrical audio formats, such as Dolby HD and Dolby Atmos.",
                            InStock = true,
                            Name = "Platin Milan 5.1 Wireless Home Theater System",
                            Price = 899.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 34,
                            CategoryID = 2,
                            Description = "SUBWOOFER INCLUDED - Wireless subwoofer is included so you can enjoy deep bass right out of the box All-in-one|| BASS BOOST - Give your bass an instant boost with the push of a button on the soundbar",
                            InStock = true,
                            Name = "Samsung HW-A450/ZA 2.1ch Soundbar with Dolby Audio (2021) , Black",
                            Price = 147.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 35,
                            CategoryID = 2,
                            Description = "Low-Profile Design and Brilliant Clarity with 6 Full-range Speakers||Powerful 5-Inch Wireless Subwoofer and Bluetooth Music Streaming||Complete Immersion with Discreet Volume Adjustable Surround Speakers||Optimized for 4K TVs with Dolby Audio 5.1 and HDMI(Cable Included)||Control with TV Remote using HDMI, Audio Cables Included for Easy Setup",
                            InStock = true,
                            Name = "Vizio V51x-J6 36-inch 5.1 Channel Home Theater Soundbar System (Renewed)",
                            Price = 169.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 36,
                            CategoryID = 2,
                            Description = "5.1 digital surround sound: Hear every detail in your Dolby Digital and DTS soundtracks the way the studio intended. Sub woofer: 165 Watts||THX certified home theater speakers: Your assurance of true cinema quality sound.Satellites : 4 x 67 W,  wall mountable||Delivers a continuous 500 watts of power, with the ability to deliver a peak of 1000 watts under certain circumstances: Thunderous, room shaking audio with deep bass you can feel",
                            InStock = true,
                            Name = "Logitech Z906 5.1 Surround Sound Speaker System - THX, Dolby Digital and DTS Digital Certified - Black",
                            Price = 351.49000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 37,
                            CategoryID = 2,
                            Description = "Bluetooth 5. 1 Home Theater Speaker System - Stream Music From Your Phone To The Built In Bluetooth Receiver, Integrated Power Amp With 700 Watts System Power, Pro Surround Function Automatically Converts Stereo To 5. 1 Sound, Fm Tuner",
                            InStock = true,
                            Name = "Acoustic Audio AA5172 700W Bluetooth Home Theater 5.1 Speaker System with FM Tuner, USB, SD Card, Remote Control, Powered Sub (6 Speakers, 5.1 Channels, Black with Gray)",
                            Price = 114.88,
                            URL = ""
                        },
                        new
                        {
                            ID = 38,
                            CategoryID = 2,
                            Description = "DOLBY ATMOS / DTS:X - Theater-quality sound that fires from the front, side and above for true audio immersion.TRUE 3.1.2CH SOUND - The complete audio entertainment experience with 3 channels,  1 subwoofer and 2 up - firing channels.",
                            InStock = true,
                            Name = "SAMSUNG 3.1.2ch Q700A Q Series Soundbar - Dolby Atmos/ DTS: X (HW-Q700A, 2021 Model), Black",
                            Price = 547.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 39,
                            CategoryID = 2,
                            Description = "Wireless Water-Resistant Speaker with Long-Lasting Battery and Handle, Black More sound all around—Engineered to deliver true 360° sound for consistent, uniform coverage from a bluetooth speaker. SoundLink Revolve II plays louder and deeper with longer battery life than SoundLink Revolve II",
                            InStock = true,
                            Name = "Bose SoundLink Revolve+ (Series II) Portable Bluetooth Speaker ",
                            Price = 329.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 40,
                            CategoryID = 2,
                            Description = "POWERFUL JBL ORIGINAL PRO SOUND: Feel your music. Flip 5's all new racetrack-shaped driver delivers bold JBL signature sound. Enjoy booming bass in a small package.",
                            InStock = true,
                            Name = "JBL FLIP 5, Waterproof Portable Bluetooth Speaker, Blue",
                            Price = 99.950000000000003,
                            URL = ""
                        },
                        new
                        {
                            ID = 41,
                            CategoryID = 2,
                            Description = "IP67 Waterproof & Durable for Outdoor, 16 Hour Battery, USB Type-C, Removable Strap, & Speakerphone, Light Blue || EXTRA BASS for deep, punchy sound",
                            InStock = true,
                            Name = "Sony SRS-XB13 EXTRA BASS Wireless Bluetooth Portable Lightweight Compact Travel Speaker",
                            Price = 48.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 42,
                            CategoryID = 2,
                            Description = "Portable Mini Bluetooth Speaker, Big Audio and Punchy bass, Integrated Carabiner, IP67 Waterproof and dustproof, 10 Hours of Playtime, Speaker for Home, Outdoor and Travel - (Blue)",
                            InStock = true,
                            Name = "JBL Clip 4",
                            Price = 79.950000000000003,
                            URL = ""
                        },
                        new
                        {
                            ID = 43,
                            CategoryID = 2,
                            Description = "WIRELESS BLUETOOTH STREAMING: Wirelessly connect up to 2 smartphones or tablets to the speaker and take turns enjoying powerful sound.||UP TO 20 HOURS OF PLAYTIME: Built -in rechargeable Li - ion 7500mAH battery supports up to 20 hours of playtime and charges your device via USB port|| IPX7 WATERPROOF: Take Charge 4 to the beach or the pool without worrying about spills or even submersion in water",
                            InStock = true,
                            Name = "JBL Charge 4 - Waterproof Portable Bluetooth Speaker - Black",
                            Price = 113.95,
                            URL = ""
                        },
                        new
                        {
                            ID = 44,
                            CategoryID = 2,
                            Description = "Portable Bluetooth Speaker, Powerful Sound and Deep Bass, IP67 Waterproof, 15 Hours of Playtime, Powerbank, JBL PartyBoost for Multi-speaker Pairing (Black)",
                            InStock = true,
                            Name = "JBL Xtreme 3",
                            Price = 299.94999999999999,
                            URL = ""
                        },
                        new
                        {
                            ID = 45,
                            CategoryID = 2,
                            Description = "River Teal - Waterproof, Durable & Portable Bluetooth Speaker - Up to 10 Hours of Play - Includes Noise-Cancelling Speakerphone & Wireless Streaming",
                            InStock = true,
                            Name = "JBL Clip 3",
                            Price = 39.950000000000003,
                            URL = ""
                        },
                        new
                        {
                            ID = 46,
                            CategoryID = 2,
                            Description = "State-of-the-art design – SoundLink Flex outdoor speaker is packed with exclusive technologies and a custom-engineered transducer for deep, clear, and immersive audio at home or on the go",
                            InStock = true,
                            Name = "Bose SoundLink Flex Bluetooth Portable Speaker, Wireless Waterproof Speaker for Outdoor Travel - Black",
                            Price = 149.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 47,
                            CategoryID = 2,
                            Description = "DAZZLING 360 DEGREES LED LIGHTS: Pulse 4 shines through the night with an amazing, high-resolution 360-degree LED lightshow.||POWERFUL JBL ORIGINAL PRO SOUND: Pulse 4 delivers JBL Signature Sound in every direction with its ingenious 360 degree speaker array.",
                            InStock = true,
                            Name = "JBL Pulse 4 - Waterproof Portable Bluetooth Speaker with Light Show - Black",
                            Price = 249.94999999999999,
                            URL = ""
                        },
                        new
                        {
                            ID = 48,
                            CategoryID = 2,
                            Description = "IP67 Waterproof & Durable for Home, Outdoor, and Travel, 24 Hour Battery, Party Lights, USB Type-C, and Speakerphone, Black||Boost your music with 2 speaker lights and multi-colored line lights and turn the lights on or off via the Fiestable App",
                            InStock = true,
                            Name = "Sony SRS-XB43 EXTRA BASS Wireless Bluetooth Powerful Portable Speaker",
                            Price = 178.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 49,
                            CategoryID = 3,
                            Description = "BRAVIA XR Full Array LED Smart Google TV with Dolby Vision HDR and Exclusive Features for The Playstation® 5 XR65X90K- 2022 Model",
                            InStock = true,
                            Name = "Sony 65 Inch 4K Ultra HD TV X90K Series",
                            Price = 1298.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 50,
                            CategoryID = 3,
                            Description = "CT-2860 High Definition Television 720p 60Hz TV, Lightweight and Slim Design, VGA/HDMI/USB Inputs, VESA Wall Mount Compatible.",
                            InStock = true,
                            Name = "28” LED HDTV by Continu.us",
                            Price = 249.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 51,
                            CategoryID = 3,
                            Description = "Brilliant 4K entertainment - Bring movies and shows to life with support for vivid 4K Ultra HD, HDR 10, HLG, and Dolby Digital Plus, and control the TV hands-free with Alexa.",
                            InStock = true,
                            Name = "Amazon Fire TV 55inch",
                            Price = 299.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 52,
                            CategoryID = 3,
                            Description = "4K Ultra HD, HDR 10, and HLG deliver a clearer and more vibrant picture with brighter colors compared to 1080p Full HD.",
                            InStock = true,
                            Name = "Amazon Fire TV 50inch 4 - Series 4K UHD smart TV",
                            Price = 469.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 53,
                            CategoryID = 3,
                            Description = "4K UHD HDR Smart TV with Alexa Built-in (UN65AU8000FXZA, 2021 Model), Black",
                            InStock = true,
                            Name = "SAMSUNG 65-Inch Class Crystal UHD AU8000 Series",
                            Price = 647.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 54,
                            CategoryID = 3,
                            Description = "Smart functionality delivers all your favorite content with over 500,000 movies and TV episodes, accessible through the simple and intuitive Roku TV |HD, Resolution: High definition (720p) resolution for excellent detail, color and contrast. Wireless Connection : 802.11ac 1x1 Dual Band",
                            InStock = true,
                            Name = "TCL 32-inch 3-Series 720p Roku Smart TV - 32S335, 2021 Model",
                            Price = 158.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 55,
                            CategoryID = 3,
                            Description = "1080p Full HD Resolution excellent detail, color, and contrast. Wireless Connection: 802.11 2x2 Dual Band || Direct-lit LED produces great picture quality with 60Hz refresh rate for fast moving action scenes with virtually no motion blur. Screw Size : M4 x 8",
                            InStock = true,
                            Name = "TCL 32-inch 1080p Roku Smart LED TV - 32S327, 2019 Model",
                            Price = 168.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 56,
                            CategoryID = 3,
                            Description = "Full Array Local Dimming - The M550 backlight panel with full array local dimming. This technology separates the LEDs into smaller, more tightly controlled lighting areas giving the television more control over the parts of the picture that need more or less lighting without affecting the other areas.",
                            InStock = true,
                            Name = "Toshiba 55-inch Class M550 Series LED 4K UHD Smart Fire TV with Hands-Free with Alexa (55M550KU, 2021 Model)",
                            Price = 799.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 57,
                            CategoryID = 3,
                            Description = "Full HD 1080p Resolution|| PurColor|| Micro Dimming Pro|| Samsung Smart TV.Mini Wall Mount and Vesa Wall Mount Compatible|| SmartThings App Support.Product Size(W x H x D) Without Stand - 36.3 x 20.9 x 2.9 inches.Stand Size(WxHxD) - 5.2 x 5.6 x 6.7 inches",
                            InStock = true,
                            Name = "SAMSUNG 40-inch Class LED Smart FHD TV 1080P (UN40N5200AFXZA, 2019 Model)",
                            Price = 227.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 58,
                            CategoryID = 3,
                            Description = "Full HD (1080p) Resolution: Full high definition (1080p) resolution for excellent detail, color, and contrast.|| Google Assistant Built -in: Search for movies and shows across thousands of available apps, get entertainment recommendations, access media playback controls, change the temperature, dim the lights, and so much more.Ask questions and see the answers on your TV, including Google Photos, your calendar, sports scores, and more.Even automate and control your smart devices.The Google Assistant is always on, ready to help, and makes life in your living room that much more relaxing.",
                            InStock = true,
                            Name = "TCL 40-inch Class 3-Series HD LED Smart Android TV - 40S334, 2021 Model",
                            Price = 198.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 59,
                            CategoryID = 3,
                            Description = "1080p High-Definition - Watch TV in crisp, clear 1080p Full HD resolution and experience a brilliant picture with the VIZIO D-Series.|| Full Array LED Backlight - Evenly distributed LEDs across the screen’s backlight deliver superior light uniformity and picture performance.",
                            InStock = true,
                            Name = "VIZIO 32-inch D-Series Full HD 1080p Smart TV with Apple AirPlay and Chromecast Built-in, Alexa Compatibility, D32f-J04, 2021 Model",
                            Price = 163.65000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 60,
                            CategoryID = 3,
                            Description = "INTELLIGENT TV PROCESSING– The 4K HDR Processor X1 delivers a picture that is smooth and clear, full of rich colors and detailed contrast.|| WIDE SPECTRUM OF COLORS - Reproduces over a billion accurate colors resulting in picture quality that is natural and precise,and closer than ever to real life,enhanced by TRILUMINOS Pro.",
                            InStock = true,
                            Name = "Sony 65 Inch 4K Ultra HD TV X80K Series: LED Smart Google TV with Dolby Vision HDR KD65X80K- 2022 Model",
                            Price = 798.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 61,
                            CategoryID = 3,
                            Description = "ULTRA-BRIGHT FOR THE OUTDOORS – The high brightness you need outside with an advanced 1,000 nit screen. Full Array Local zone dimming for brighter brights and darker darks. IP55-rated aluminum exterior made for the elements – including rain & snow.",
                            InStock = true,
                            Name = "SunBrite Veranda 3 Series 55-inch Full Shade Outdoor Smart TV (2022) | 4K Ultra HD HDR LED Weatherproof Television - 1,000 nit Ultra Bright Screen SB-V3-55-4KHDR-BL",
                            Price = 2898.9499999999998,
                            URL = ""
                        },
                        new
                        {
                            ID = 62,
                            CategoryID = 3,
                            Description = "1080p resolution View your favorite movies, shows and games in high definition. || Alexa voice control - The Alexa Voice Remote lets you easily control your entertainment,search across apps, switch inputs, and more using just your voice.Press and hold the voice button and ask Alexa to easily find, launch, and control content, and even switch to cable.",
                            InStock = true,
                            Name = "Insignia 32-inch Class F20 Series Smart Full HD 1080p Fire TV (NS-32F202NA22, 2021 Model)",
                            Price = 199.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 63,
                            CategoryID = 3,
                            Description = "Stunning 4K Ultra HD: 4K resolution delivers stunning detail and remarkable visual experience.|| High Dynamic Range: HDR delivers bright and accurate colors for a lifelike viewing experience.|| Google Assistant Built -in",
                            InStock = true,
                            Name = "TCL 50-inch Class 4-Series 4K UHD HDR Smart Android TV - 50S434, 2021 Model",
                            Price = 317.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 64,
                            CategoryID = 3,
                            Description = "High Dynamic Range: HDR delivers bright and accurate colors for a lifelike viewing experience.|| Stunning 4K Ultra HD: 4K resolution delivers stunning detail and a remarkable visual experience.|| Easy Voice Control",
                            InStock = true,
                            Name = "TCL 75-inch Class 4-Series 4K UHD HDR Smart Roku TV – 75S435, 2021 Model",
                            Price = 699.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 65,
                            CategoryID = 3,
                            Description = "CRYSTAL PROCESSOR 4K: This ultra fast processor transforms everything you watch into stunning 4K.|| MOTION RATE 240: Minimizes motion blur on screen,so action packed movies and sports stay smooth and crisp.|| SMART TV POWERED BY TIZEN TM: Go beyond Smart TV with next gen apps, super easy control,and a host of enhancements that elevate the TV watching experience.",
                            InStock = true,
                            Name = "SAMSUNG 85-Inch Class Crystal 4K UHD AU8000 Series HDR Smart TV (UN85AU8000FXZA, 2021 Model)",
                            Price = 1597.99,
                            URL = ""
                        },
                        new
                        {
                            ID = 66,
                            CategoryID = 3,
                            Description = "Regza Engine 4K is Toshiba’s high performance 4K engine for stunning picture quality, with ultra essential PQ technology combined with high quality LCD panel, you can get an incredible ultra HD 4K images with breath-taking picture quality.",
                            InStock = true,
                            Name = "Toshiba 43-inch Class C350 Series LED 4K UHD Smart Fire TV (43C350KU, 2021 Model)",
                            Price = 329.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 67,
                            CategoryID = 3,
                            Description = "4K Ultra High Definition: More pixels on the screen produces a more clear and succinct picture making content look more realistic and true to life. Combined with Hisense's AI UHD Upscaler , non 4K content will get enhanced to near 4K quality.",
                            InStock = true,
                            Name = "Hisense A6 Series 55-Inch 4K UHD Smart Google TV (55A6H, 2022 New Model)",
                            Price = 319.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 68,
                            CategoryID = 3,
                            Description = "Stunning 4K Ultra HD: 4K resolution delivers stunning detail and remarkable visual experience.|| High Dynamic Range: HDR delivers bright and accurate colors for a lifelike viewing experience.",
                            InStock = true,
                            Name = "TCL 55-Inch Class 4 - Series 4K UHD HDR Smart Google TV – 55S446, 2022 Model",
                            Price = 339.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 69,
                            CategoryID = 3,
                            Description = "4K UltraHD delivers more than four times the resolution of a regular 1080p highdefinition screen. Along with over 8.3 million pixels, inside you'll find a powerful full array LED backlight at work creating a sharper, more colorful picture.",
                            InStock = true,
                            Name = "Hisense 55-Inch Class R6 Series Dolby Vision HDR 4K UHD Roku Smart TV with Alexa Compatibility (55R6G, 2021 Model)",
                            Price = 449.94999999999999,
                            URL = ""
                        },
                        new
                        {
                            ID = 70,
                            CategoryID = 3,
                            Description = "SMART HUB: Access to Streaming apps like Netflix, YouTube, Apple TV, Disney + and local OTT|| IMPROVED CONNECTIVITY: USB - C offers a single connection architecture for a clutter-free and stress - free environment; Wirelessly connect to and mirror PCs remotely on the Smart Monitor for a PC-less environment.",
                            InStock = true,
                            Name = "SAMSUNG M8 Series 32-Inch 4K UHD Smart Monitor & Streaming TV with Slim-fit Webcam (LS32BM801UNXGO)",
                            Price = 699.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 71,
                            CategoryID = 4,
                            Description = "Factory Unlocked Android Smartphone, 128GB, 6.5” FHD Super AMOLED Screen, Long Battery Life, US Version, Black",
                            InStock = true,
                            Name = "SAMSUNG Galaxy A53 5G A Series Cell Phone",
                            Price = 449.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 72,
                            CategoryID = 4,
                            Description = "This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks (e.g. AT&T, T-Mobile, Sprint, Verizon, US Cellular, Cricket, Metro, Tracfone, Mint Mobile, etc.).",
                            InStock = true,
                            Name = "Apple iPhone 11, 64GB, Black - Unlocked (Renewed)",
                            Price = 339.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 73,
                            CategoryID = 4,
                            Description = "This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks (e.g. AT&T, T-Mobile, Sprint, Verizon, US Cellular, Cricket, Metro, Tracfone, Mint Mobile, etc.).",
                            InStock = true,
                            Name = "Apple iPhone XR, 64GB, Black - Unlocked (Renewed)",
                            Price = 231.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 74,
                            CategoryID = 4,
                            Description = "This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks (e.g. AT&T, T-Mobile, Sprint, Verizon, US Cellular, Cricket, Metro, Tracfone, Mint Mobile, etc.).",
                            InStock = true,
                            Name = "Samsung Galaxy S10, 128GB, Prism Black - Unlocked (Renewed)",
                            Price = 322.57999999999998,
                            URL = ""
                        },
                        new
                        {
                            ID = 75,
                            CategoryID = 4,
                            Description = "Fully Unlocked: Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.), both domestically and internationally.",
                            InStock = true,
                            Name = "Samsung Galaxy S10e, 128GB, Prism Black - Unlocked (Renewed)",
                            Price = 170.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 76,
                            CategoryID = 4,
                            Description = "Factory Unlocked Android smartphone, 256GB, 8K Camera & Video, Brightest Display Screen, S Pen, Long Battery Life, Fast 4nm Processor, US Version, Phantom Black",
                            InStock = true,
                            Name = "SAMSUNG Galaxy S22 Ultra Cell Phone",
                            Price = 1049.99,
                            URL = ""
                        },
                        new
                        {
                            ID = 77,
                            CategoryID = 4,
                            Description = "Android Phone - Unlocked Smartphone with Wide and Ultrawide Lens - 128GB - Stormy Black",
                            InStock = true,
                            Name = "Google Pixel 6 – 5G",
                            Price = 599.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 78,
                            CategoryID = 4,
                            Description = "5G Android Smartphone | 6.7” QHD+ Display | 12GB+256GB | U.S. Unlocked | Triple Camera co-Developed with Hasselblad | Volcanic Black",
                            InStock = true,
                            Name = "OnePlus 10 Pro",
                            Price = 969.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 79,
                            CategoryID = 4,
                            Description = "5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, Pro Grade Camera, 30X Space Zoom, Night Mode, US Version, Cloud Navy",
                            InStock = true,
                            Name = "SAMSUNG Galaxy S20 FE",
                            Price = 599.99000000000001,
                            URL = ""
                        },
                        new
                        {
                            ID = 80,
                            CategoryID = 4,
                            Description = "256GB, Aura Black - Fully Unlocked (Renewed) Fully Unlocked: Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.), both domestically and internationally.",
                            InStock = true,
                            Name = "Samsung Galaxy Note 10",
                            Price = 287.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 81,
                            CategoryID = 4,
                            Description = "256GB, Aura Black - Fully Unlocked (Renewed) Fully Unlocked: Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.), both domestically and internationally.",
                            InStock = true,
                            Name = "Samsung Galaxy Note 10+",
                            Price = 342.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 82,
                            CategoryID = 4,
                            Description = "This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks (e.g. AT&T, T-Mobile, Sprint, Verizon, US Cellular, Cricket, Metro, Tracfone, Mint Mobile, etc.).",
                            InStock = true,
                            Name = "Apple iPhone 12, 64GB, Blue - Fully Unlocked (Renewed)",
                            Price = 1049.99,
                            URL = ""
                        },
                        new
                        {
                            ID = 83,
                            CategoryID = 4,
                            Description = "*Charging Cube is Not Included*, 6.5-Inch,Super AMOLED,  120Hz,  800 nits,1080x2400 pixels, 5000mAh Battery128GB ROM,   6GB RAM,  Exynos 1280(5 nm), Octa - core,  Mali - G68,Android 12,One UI 4.1|| Rear Camera: 64MP, f / 1.8 + 12MP, f / 2.2 + 5MP,   f / 2.4 + 5MP, f / 2.4,Front Camera: 32MP,f / 2.2",
                            InStock = true,
                            Name = "Samsung Galaxy A53 5G (SM-A536E/DS)",
                            Price = 320.00999999999999,
                            URL = ""
                        },
                        new
                        {
                            ID = 84,
                            CategoryID = 4,
                            Description = "6.1-inch Super Retina XDR displayCinematic mode adds shallow depth of field and shifts focus automatically in your videosAdvanced dual - camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recordingA15 Bionic chip for lightning - fast performance",
                            InStock = true,
                            Name = "Apple iPhone 13 (256GB, Blue) [Locked]",
                            Price = 929.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 85,
                            CategoryID = 4,
                            Description = "6.1-inch Super Retina XDR display with ProMotion for a faster, more responsive feelCinematic mode adds shallow depth of field and shifts focus automatically in your videosPro camera system with new 12MP Telephoto, Wide, and Ultra Wide cameras; LiDAR Scanner; 6x optical zoom range; macro photography; Photographic Styles, ProRes video, Smart HDR 4, Night mode, Apple ProRAW, 4K Dolby Vision HDR recording12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recordingA15 Bionic chip for lightning - fast performanceUp to 22 hours of video playbackDurable design with Ceramic Shield",
                            InStock = true,
                            Name = "Apple iPhone 13 Pro (512GB, Graphite) [Locked]",
                            Price = 1299.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 86,
                            CategoryID = 4,
                            Description = "5.4-inch Super Retina XDR display Cinematic mode adds shallow depth of field and shifts focus automatically in your videosAdvanced dual - camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recordingA15 Bionic chip for lightning - fast performanceUp to 17 hours of video playbackDurable design with Ceramic Shield",
                            InStock = true,
                            Name = "Apple iPhone 13 Mini (128GB, Starlight) [Locked]",
                            Price = 729.0,
                            URL = ""
                        },
                        new
                        {
                            ID = 87,
                            CategoryID = 4,
                            Description = "6.7-Inch Super Retina XDR display with ProMotion. 5G Superfast downloads,high ? quality streamingCinematic mode in 1080p at 30 fps.Dolby Vision HDR video recording up to 4K at 60 fps. 6X Optical zoom rangeA15 Bionic chip.New 6 - core CPU with 2 performance and 4 efficiency cores.New 5 - core GPU.New 16 - core Neural EngineUp to 28 hours video playback.Face ID.Ceramic Shield front.Surgical - grade stainless steelWater resistant to a depth of 6 meters for up to 30 minutes.Compatible with MagSafe accessories and wireless chargers",
                            InStock = true,
                            Name = "Apple iPhone 13 Pro Max, 128GB, Graphite - Unlocked (Renewed)",
                            Price = 1147.95,
                            URL = ""
                        },
                        new
                        {
                            ID = 88,
                            CategoryID = 4,
                            Description = "This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks (e.g. AT&T, T-Mobile, Sprint, Verizon, US Cellular, Cricket, Metro, Tracfone, Mint Mobile, etc.).",
                            InStock = true,
                            Name = "Apple iPhone 11 Pro, 64GB, Space Gray - Unlocked (Renewed)",
                            Price = 459.13999999999999,
                            URL = ""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "administrator",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "editor",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "user",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissions",
                            ClaimValue = "create",
                            RoleId = "administrator"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissions",
                            ClaimValue = "delete",
                            RoleId = "administrator"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissions",
                            ClaimValue = "create",
                            RoleId = "editor"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissions",
                            ClaimValue = "update",
                            RoleId = "editor"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissions",
                            ClaimValue = "create",
                            RoleId = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("E_Commerce.Models.ApplicationUser", b =>
                {
                    b.HasOne("E_Commerce.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartID");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("E_Commerce.Models.Product", b =>
                {
                    b.HasOne("E_Commerce.Models.Cart", null)
                        .WithMany("Products")
                        .HasForeignKey("CartID");

                    b.HasOne("E_Commerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("E_Commerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce.Models.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
